### ISSUE TITLE
Input files

### ISSUE THREAD

**Issue by Handymanalan** [KennthShang/CHEER#1]
Hi,

Can I classify viral contigs (fasta files) extracted from metagenomes?

I used VirSorter2 and MARVEL to extract those contigs, but am not sure your program works on fasta files or just reads.

Cheers

Alan

**Comment by KennthShang** [comment]
Of course, we supply a method that will cut the long contigs into 250bp input then do the majority voting for each contig. But I am not sure about the dataset is fit the model since the pre-trained model is only trained on the 6 RNA viruses ( you can find them in the "Tools/corresponding id.xlsx". If you want the model that can predict more labels, please re-train it.

**Comment by Handymanalan** [comment]
Thanks I will try that. What's the method? Do I need to specify it in the command line?

**Comment by KennthShang** [comment]
You can run it follow the README file. It's a built-in function. No other command-line is required.
